version: '3'
services:
  redis:
    image: redis
    container_name: spring.redis
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    networks:
      - spring
networks:
 spring:
  external: true