zuul:
  routes:
    ui:
      url: http://localhost:8081
    resource:
      url: http://localhost:9000
  sensitive-headers:

spring:
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379